BOOTLOADER = atmel-dfu
CONVERT_TO = elite_pi

AUTO_SHIFT_ENABLE = yes
CAPS_WORD_ENABLE = yes
EXTRAKEY_ENABLE = yes
TAP_DANCE_ENABLE = yes
COMBO_ENABLE = yes
REPEAT_KEY_ENABLE = yes
SEND_STRING_ENABLE = yes

RGBLIGHT_ENABLE = yes
RGB_MATRIX_ENABLE = no
OLED_ENABLE = yes
OLED_DRIVER = ssd1306
